server:
  port: 9000

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/grocerylister
    username: grocerylister
    password: grocerylister

---

spring:
  profiles: dev-local
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/grocerylister
    username: grocerylister
    password: grocerylister

---

spring:
  profiles: dev-docker
  datasource:
    url: jdbc:postgresql://10.0.3.2:5432/grocerylister
    username: grocerylister
    password: grocerylister


---

spring:
  profiles: local-production
  datasource:
    url: jdbc:postgresql://rds-postgres-johannsen-cloud.cq3xeric7bhh.us-east-1.rds.amazonaws.com:5432/grocerylister
    username: grocerylister
    password: grocerylister

---

spring:
  profiles: production
  datasource:
    url: jdbc:postgresql://rds-postgres-johannsen-cloud.cq3xeric7bhh.us-east-1.rds.amazonaws.com:5432/grocerylister
    username: grocerylister
    password: grocerylister

